#!/usr/bin/env python3
"""Generate src/lift_main.c — host entry that invokes lifted boot/code symbols."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml

from tools.decomp.export_symbols import load_functions_yaml
from tools.decomp.symbol_kind import lookup_symbol_kind
from tools.decomp.workspace import resolve_in_repo

FUNC_DEF = re.compile(
    r"^(?:(?:void\s*\*|void|u32|int|unsigned\s+(?:char|short|int)\s*\*)\s+)"
    r"(\w+)\s*\(([^)]*)\)\s*\{",
    re.MULTILINE,
)
RODATA_MARKER = "ROM constant block"


def _collect_lifted_functions(src_dirs: list[Path]) -> list[tuple[str, str, Path]]:
    """Return (name, params, path) for each lifted code function."""
    rows: list[tuple[str, str, Path]] = []
    seen: set[str] = set()
    for src_dir in src_dirs:
        if not src_dir.is_dir():
            continue
        for path in sorted(src_dir.glob("*.c")):
            text = path.read_text(encoding="utf-8", errors="replace")
            if RODATA_MARKER in text:
                continue
            for match in FUNC_DEF.finditer(text):
                name = match.group(1)
                if name in seen:
                    continue
                seen.add(name)
                rows.append((name, match.group(2).strip(), path))
    return sorted(rows, key=lambda r: r[0])


def _pick_entry(functions_yaml: Path, lifted_names: set[str]) -> tuple[str, str]:
    """Return (entry_symbol, note). Prefer maincpu_reset_entry (boot header IP @ 0x420)."""
    preferred = (
        "maincpu_reset_entry",
        "boot_entry",
    )
    for name in preferred:
        if name in lifted_names:
            note = "boot ROM header initial IP @ 0x420" if name == "maincpu_reset_entry" else "PRCB dispatch @ 0x310"
            return name, note

    # First boot code symbol by address from yaml.
    boot_code: list[tuple[int, str]] = []
    for row in load_functions_yaml(functions_yaml):
        name = str(row.get("name", ""))
        if name not in lifted_names:
            continue
        if lookup_symbol_kind(name, int(row.get("address", 0))) == "rodata":
            continue
        section = str(row.get("section", ""))
        if "boot" in section:
            boot_code.append((int(row.get("address", 0)), name))
    if boot_code:
        boot_code.sort()
        return boot_code[0][1], f"first boot code symbol @ 0x{boot_code[0][0]:x}"

    if lifted_names:
        name = sorted(lifted_names)[0]
        return name, "first lifted symbol"
    return "maincpu_reset_entry", "fallback (no lifted symbols found)"


def generate_main(
    *,
    src_dirs: list[Path],
    functions_yaml: Path,
    entry_override: str | None = None,
) -> str:
    functions = _collect_lifted_functions(src_dirs)
    lifted_names = {name for name, _, _ in functions}

    entry, entry_note = _pick_entry(functions_yaml, lifted_names)
    if entry_override:
        entry = entry_override

    lines = [
        "/* Auto-generated by tools/decomp/gen_lift_main.py — do not edit. */",
        "/* Regenerate: make lift-main */",
        "",
        "#include <stdio.h>",
        "",
        '#include "i960_host.h"',
        '#include "i960_lift.h"',
        "",
    ]

    for name, params, path in functions:
        rel = path.name
        src_text = path.read_text(encoding="utf-8", errors="replace")
        sig_match = re.search(
            rf"^((?:void\s*\*|void|u32|int)[^{{]*)\b{name}\s*\(",
            src_text,
            re.MULTILINE,
        )
        if sig_match:
            ret = sig_match.group(1).strip()
            lines.append(f"extern {ret} {name}({params}); /* {rel} */")
        elif params:
            lines.append(f"extern void {name}({params}); /* {rel} */")
        else:
            lines.append(f"extern void {name}(void); /* {rel} */")
    lines.append("")

    lines.extend(
        [
            f"/* Entry: {entry} ({entry_note}) */",
            "int main(void)",
            "{",
            "    i960_host_load_rom();",
            "    i960_host_reset();",
            "",
        ]
    )

    if entry == "boot_entry":
        lines.extend(
            [
                "    /* boot_entry waits on HW timer @ fp+0x40 — use host wrapper */",
                "    boot_entry_host(0, 0, 0);",
            ]
        )
    elif entry == "maincpu_reset_entry":
        lines.append("    maincpu_reset_entry(0, 0, 0);")
    else:
        lines.append(f"    {entry}(0, 0, 0);")

    lines.extend(
        [
            "",
            "    return (int)g0;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate lift_main.c host entry")
    ap.add_argument(
        "--src-dir",
        action="append",
        dest="src_dirs",
        type=Path,
        default=None,
        help="Lift output dirs (default: src/boot, src/libc)",
    )
    ap.add_argument("--functions", type=Path, default=Path("symbols/functions.yaml"))
    ap.add_argument("--entry", default=None, help="Override entry symbol")
    ap.add_argument("-o", "--out", type=Path, default=Path("src/lift_main.c"))
    args = ap.parse_args()

    src_dirs = [resolve_in_repo(p) for p in (args.src_dirs or [Path("src/boot"), Path("src/libc")])]
    functions_yaml = resolve_in_repo(args.functions)
    out = resolve_in_repo(args.out)

    text = generate_main(
        src_dirs=src_dirs,
        functions_yaml=functions_yaml,
        entry_override=args.entry,
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
